### ISSUE TITLE
Windows Testing for new DevMateria

### ISSUE THREAD

**Issue by WilliamRADFunk** [ucfopen/Materia-Widget-Dev-Kit#35]
This is a deferred issue since we currently have no developers working in Windows.

This is in reference to the completed issue #715, specifically branch: "the-big-gulp" that has been merged into master most likely before this issue is looked at.

At the time of this issue's creation, the changes were QAed on Mac already.

**Comment by clpetersonucf** [comment]
I think we can consider this NYI for now.
