### ISSUE TITLE
Add support for building markdown guide files

### ISSUE THREAD

**Issue by nathaned** [ucfopen/Materia-Widget-Dev-Kit#45]
Convert `.md` files to `.html` guides given a template

Example in Crossword:
1. Create markdown file in widget's `src/_helper-docs/player.md`
2. Create HTML template in widget's `src/_helper-docs/playerTemplate.html`
3. Add `rules.loadGuideTemplate` to webpack rules
4. Add `'guides/player.html': [__dirname + '/src/_helper-docs/playerTemplate.html']` to webpack entries (same for creator)

running `yarn build` will then compile the markdown into html, and insert that into the given template, then export it to `build/guides/player.html`

**Comment by FrenjaminBanklin** [comment]
This was handled in v2.4.2.
